git:
  url: "git@github.com:kalsadaram/k3s-homelab.git"
  branch: master
  path: deployments
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux