
git:
  url: "git@github.com:kalsadaram/k3s-homelab.git"
  branch: master
  path: deployments
  user: "kalsadaram"
  email: "kalsadaram@users.noreply.github.com"
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false