helmOperator:
  create: false
git:
  url: "git@github.com:kalsadaram/k3s-homelab"
image:
  repository: docker.io/fluxcd/flux
  tag: 1.20.0
registry:
  rps: 50
  burst: 50
memcached:
  tolerations:
  - key: "arm"
    operator: "Exists"
additionalArgs:
- --connect=ws://fluxcloud
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false