---

- name: Download & install k3
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-name {{ hostname }} --flannel-backend=host-gw" sh -s -
  args:
    warn: no

- name: Fix Unable to read /etc/rancher/k3s/k3s.yaml issue
  shell: sudo chmod -R 777 /etc/rancher/k3s/k3s.yaml
  args:
    warn: no

- name: Download and Install Helm3
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    warn: no

- name: Install Fluxctl
  shell: sudo snap install fluxctl --classic
  args:
    warn: no

- name: Create flux namespace
  shell: kubectl apply -f https://raw.githubusercontent.com/{{ GIT_AUTHUSER }}/{{ GIT_REPO_NAME }}/master/deployments/flux/namespace.yaml
  args:
    warn: no

- name: Add fluxcd charts
  shell: helm repo add fluxcd https://charts.fluxcd.io
  args:
    warn: no

- name: update Helm
  shell: helm repo update
  args:
    warn: no

# Below won't work Manual steps
# helm upgrade --install flux --values https://raw.githubusercontent.com/kalsadaram/k3s-homelab/master/deployments/flux/flux-values.yaml --namespace flux fluxcd/flux --kubeconfig /etc/rancher/k3s/k3s.yaml
# kubectl -n flux logs deployment/flux | grep identity.pub | cut -d '"' -f2

#- name: Heml Install
#  shell: helm upgrade --install flux --values https://raw.githubusercontent.com/{{ GIT_AUTHUSER }}/{{ GIT_REPO_NAME }}/master/deployments/flux/flux-values.yaml --namespace flux fluxcd/flux  --kubeconfig /etc/rancher/k3s/k3s.yaml
#  args:
#    warn: no
...