---

- name: Download & install k3
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable servicelb traefik metrics-server --flannel-backend=host-gw" sh -s -
  args:
    warn: no

- name: Fix Unable to read /etc/rancher/k3s/k3s.yaml issue
  shell: sudo chmod -R 777 /etc/rancher/k3s/k3s.yaml
  args:
    warn: no

- name: Create storage class for the cluster
  shell: kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
    args:
    warn: no

- name: Install Fluxctl
  shell: sudo snap install fluxctl --classic
  args:
    warn: no

- name: Download and Install Helm3
  shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    warn: no
...