---
- name: Clone k3s-homelab from GitHub.
  git:
    repo: https://github.com/KalSadaram/k3s-homelab.git
    dest: "{{ k3s_homelab_path }}"
  register: k3s_homelab

- name: Initiate Flux and Helm Operator
  args:
    warn: no
  shell: |
    kubectl apply -f "{{ k3s_homelab_path }}"/deployments/flux/namespace.yaml | helm repo add fluxcd https://charts.fluxcd.io |
    helm repo update | helm upgrade --install flux --values deployments/flux/flux-values.yaml --namespace flux fluxcd/flux

