---
- hosts: k3s_master
  become: true
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    - include_role:
        name: pre-reqs
      tags:
        - pre-req
    - include_role:
        name: system
      tags:
        - system
    - include_role:
        name: k3s
    - include_role:
        name: git